
apiVersion : apps/v1
kind: Deployment
metadata:
  name: testregistry
  labels:
    app: testregistry 
spec:
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: testregistry
  template:
    metadata:
      labels:
        app: testregistry 
    spec:
      containers:
        - name: testregistry 
          image: dockerregistry15.azurecr.io/testregistry:235
          ports:
          - containerPort: 80
          envFrom:
          - secretRef:
             name: secret

---
