apiVersion: v1
kind: Service
metadata:
    name: testregistry
spec:
    type: ClusterIP
    ports:
     - protocol: TCP 
       port: 8080
       targetPort: 8080
    selector:
        app: testregistry