apiVersion : apps/v1
kind: Deployment
metadata:
  name: weighttrackerkubernetes 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weighttrackerkubernetes
  template:
    metadata:
      labels:
        app: weighttrackerkubernetes 
    spec:
      containers:
        - name: weighttrackerkubernetes 
          image: dockerregistry15.azurecr.io/weighttrackerkubernetes
          ports:
          - containerPort: 8080